"""empty message

Revision ID: a1041f7d683b
Revises: 
Create Date: 2020-11-29 15:35:30.975769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1041f7d683b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Credits', sa.Integer(), nullable=False),
    sa.Column('DisciplineName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Group', sa.String(length=50), nullable=False),
    sa.Column('LastName', sa.String(length=50), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('DisciplineID', sa.Integer(), nullable=False),
    sa.Column('Mark', sa.Integer(), nullable=False),
    sa.Column('Passed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['DisciplineID'], ['disciplines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('StudentID', sa.Integer(), nullable=False),
    sa.Column('MarksID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MarksID'], ['marks.id'], ),
    sa.ForeignKeyConstraint(['StudentID'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('marks')
    op.drop_table('student')
    op.drop_table('disciplines')
    # ### end Alembic commands ###
